

/*-------------Q4-----------------------*/

ALTER TABLE ABONNE
ADD DATE_NAI DATE;
ALTER TABLE ABONNE ADD TYPE_AB VARCHAR(25) CHECK (TYPE_AB IN ('ADULTE', 'ENFANT'));
ALTER TABLE ABONNE ADD CAT_AB VARCHAR(25) CHECK (CAT_AB IN ('REGULIER', 'OCCASIONNEL', 'A_PROBLEME', 'EXCLU'));

/*-------------Q5-----------------------*/

ALTER TABLE ABONNE MODIFY TARIF NUMERIC(5,0);
/*-------------Q6-----------------------*/

CREATE TABLE AUTEUR (
	NUM_AUT NUMERIC (8,0),
	NOM VARCHAR(25),
	PRENOM VARCHAR(25),
	NATIONALITE VARCHAR(25),
	CONSTRAINT PK_NUM_AUT PRIMARY KEY (NUM_AUT)
	);
ALTER TABLE LIVRE ADD NUM_AUT NUMERIC(8,0);
ALTER TABLE LIVRE ADD CONSTRAINT FK_NUM_AUT FOREIGN KEY (NUM_AUT) REFERENCES AUTEUR (NUM_AUT);

/*-------------Q7-----------------------*/

ALTER TABLE MOT_CLEF ADD MOT_PARENT VARCHAR(25);
ALTER TABLE MOT_CLEF ADD CONSTRAINT FK_MOT FOREIGN KEY (MOT_PARENT) REFERENCES MOT_CLEF (MOT);

INSERT INTO MOT_CLEF VALUES ('ROOT',null);
INSERT INTO MOT_CLEF VALUES ('PROGRAMMATION', 'INFORMATIQUE');
INSERT INTO MOT_CLEF VALUES ('MODEL REALTIONNEL', 'BASES DE DONNEES');
INSERT INTO MOT_CLEF VALUES ('MODELES ORIENTES OBJETS', 'BASES DE DONNEES');

UPDATE MOT_CLEF
SET MOT_PARENT = 'ROOT'
WHERE MOT = 'MEDECINE';
UPDATE MOT_CLEF
SET MOT_PARENT = 'ROOT'
WHERE MOT = 'LITTERATURE';
UPDATE MOT_CLEF
SET MOT_PARENT = 'ROOT'
WHERE MOT = 'SCIENCES';
UPDATE MOT_CLEF
SET MOT_PARENT = 'SCIENCES'
WHERE MOT = 'INFORMATIQUE';
UPDATE MOT_CLEF
SET MOT_PARENT = 'INFORMATIQUE'
WHERE MOT = 'BASES DE DONNEES';



/*-------------Q8-----------------------*/
/*-------------Q4-----------------------*/
/*-------------Q4-----------------------*/
/*-------------Q4-----------------------*/
